### ISSUE TITLE
error MT5210

### ISSUE THREAD

**Issue by sidmurali0885** [Vidyo/VidyoConnector-xamarin#10]
Not able to build this project. Keep getting Native linking failed error. See below for log. Please advise.

/Users/siddharthmurali/Desktop/VidyoConnector-xamarin-master/VidyoConnector.iOS/clang: Error: linker command failed with exit code 1 (use -v to see invocation) (VidyoConnector.iOS)
/Users/siddharthmurali/Desktop/VidyoConnector-xamarin-master/VidyoConnector.iOS/error MT5209: Error: warning: directory not found for option '-L../VidyoClient-iOSSDK/lib/ios' (VidyoConnector.iOS) Native linking
/Users/siddharthmurali/Desktop/VidyoConnector-xamarin-master/VidyoConnector.iOS/error MT5209: Error: warning: directory not found for option '-L../VidyoClient-iOSSDK/lib/ios' (VidyoConnector.iOS) Native linking
/Users/siddharthmurali/Desktop/VidyoConnector-xamarin-master/VidyoConnector.iOS/error MT5209: Error: warning: directory not found for option '-L../VidyoClient-iOSSDK/lib/ios' (VidyoConnector.iOS) Native linking
/Users/siddharthmurali/Desktop/VidyoConnector-xamarin-master/VidyoConnector.iOS/error MT5209: Error: warning: directory not found for option '-L../VidyoClient-iOSSDK/lib/ios' (VidyoConnector.iOS) Native linking
/Users/siddharthmurali/Desktop/VidyoConnector-xamarin-master/VidyoConnector.iOS/error MT5209: Error: warning: directory not found for option '-L../VidyoClient-iOSSDK/lib/ios' (VidyoConnector.iOS) Native linking
/Users/siddharthmurali/Desktop/VidyoConnector-xamarin-master/VidyoConnector.iOS/error MT5209: Error: warning: directory not found for option '-L../VidyoClient-iOSSDK/lib/ios' (VidyoConnector.iOS) Native linking
/Users/siddharthmurali/Desktop/VidyoConnector-xamarin-master/VidyoConnector.iOS/error MT5209: Error: warning: directory not found for option '-F../VidyoClient-iOSSDK/lib/ios' (VidyoConnector.iOS) Native linking
/Users/siddharthmurali/Desktop/VidyoConnector-xamarin-master/VidyoConnector.iOS/error MT5209: Error: framework not found VPX (VidyoConnector.iOS) Native linking
/Users/siddharthmurali/Desktop/VidyoConnector-xamarin-master/VidyoConnector.iOS/MTOUCH: Error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -L../VidyoClient-iOSSDK/lib/ios -lcrypto -L../VidyoClient-iOSSDK/lib/ios -lopus -L../VidyoClient-iOSSDK/lib/ios -lspeex -L../VidyoClient-iOSSDK/lib/ios -lsrtp -L../VidyoClient-iOSSDK/lib/ios -lssl -L../VidyoClient-iOSSDK/lib/ios -lVidyoClient (MT5201) (VidyoConnector.iOS)
/Users/siddharthmurali/Desktop/VidyoConnector-xamarin-master/VidyoConnector.iOS/MTOUCH: Error MT5202: Native linking failed. Please review the build log. (MT5202) (VidyoConnector.iOS)

**Comment by pfuternik** [comment]
Hello, did you follow the steps precisely in the "Importing VidyoClient iOS SDK" section of the README, particularly if you are building on Windows?

Did you place the VidyoConnector.IOS directly under the main directory, see attached?
<img width="244" alt="screen shot 2018-11-28 at 3 44 46 pm" src="https://user-images.githubusercontent.com/24925258/49181147-993bb780-f324-11e8-905e-10fd7f253b2f.png">
