### ISSUE TITLE
Android app crash after call disconnects

### ISSUE THREAD

**Issue by lalu5585** [Vidyo/VidyoConnector-xamarin#13]
Hello Team,

My android app is crashing after disconnecting call.

here is my logs : 

[art] Throwing OutOfMemoryError "PushLocalFrame"
[art] Not gen hprof when OOME
[vidyo-sdk] 2018-12-06 12:38:52.547 +00:00|WARNING |LmiNetworkInter|Network Interfa|Unable to push JNI stack frame
[vidyo-sdk] 2018-12-06 12:38:52.547 +00:00|WARNING |LmiNetworkInter|Network Interfa|Unable to push JNI stack frame
[art] JNI DETECTED ERROR IN APPLICATION: JNI GetArrayLength called with pending exception 'java.lang.OutOfMemoryError' thrown in unknown throw location
[art]     in call to GetArrayLength
[art] "Thread-27342" prio=7 tid=62 Runnable
[art]   | group="main" sCount=0 dsCount=0 obj=0x12c674c0 self=0x7f4ff30800
[art]   | sysTid=10714 nice=-4 cgrp=default sched=0/0 handle=0x7f6f009000
[art]   | state=R schedstat=( 435423791 87094914 1111 ) utm=32 stm=11 core=0 HZ=100
[art]   | stack=0x7f4adf1000-0x7f4adf3000 stackSize=1008KB
[art]   | held mutexes= "mutator lock"(shared held)
[art]   (no managed stack frames)
[libc++abi] terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
[vidyo-sdk] 2018-12-06 12:38:52.594 +00:00|WARNING |LmiAudioPlaybac|[System thread]|Audio playback device Speaker (0): Playback get samples function took longer than the time reflected by the number of samples requested by 328 microseconds.
[CameraFramework] handleMessage: 16

[vidyo-sdk] 2018-12-05 10:35:39.631 +00:00|INFO    |VidyoConnector |[System thread]|VidyoConnectorDestruct
[vidyo-sdk] 2018-12-05 10:35:39.631 +00:00|INFO    |VidyoConnector |[System thread]|VidyoConnectorTerminate
[vidyo-sdk] 2018-12-05 10:35:39.632 +00:00|INFO    |VidyoClient    |[System thread]|VidyoEndpointDestruct
[LmiScreenManagerJava] LmiScreenManager stopped in java
[vidyo-sdk] 2018-12-05 10:35:39.647 +00:00|INFO    |VidyoClient    |[System thread]|VidyoLocalRendererDestruct 0x7f418e3800
[art] Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[59,tid=23575,Native,Thread*=0x7f51426000,peer=0x12f41340,"Thread-22061"]
Thread finished:  #15
[vidyo-sdk] 2018-12-05 10:35:39.670 +00:00|INFO    |VidyoClient    |[System thread]|VidyoLocalRendererParticipantDestruct 0x7f4ffe9580
[art] Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[63,tid=23572,Native,Thread*=0x7f3bf8c800,peer=0x12f6e6a0,"Thread-22104"]
Thread finished:  #19
[art] Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[62,tid=23571,Native,Thread*=0x7f4ff6e000,peer=0x12f69a00,"Thread-22088"]
Thread finished:  #18

let me know if you need more details.

Thanks

**Comment by tmelko-vidyo** [comment]
Hello,
Please describe how are you disconnecting from the call? Which Vidyo Client API's involved and what is the call flow?
The right way is to call: 
1) _connector.Disconnect();
2) receive OnDisconnected(Connector.ConnectorDisconnectReason reason); and popup the view from here;
3) Or release _connector instance upon page popup with _connector.Disable(); but consider that you have to construct it again once open video page next time.

**Comment by lalu5585** [comment]
Hello Sir,

I am using vidyo xamarin library for integrating video call functionality. 
here is the link : https://github.com/Vidyo/VidyoConnector-xamarin

here is the code for connecting and disconnecting call :


        void OnConnectButtonClicked(object sender, EventArgs args)
        {
            _logger.Log("DEBUG: V2MDVideoPage->OnConnectButtonClicked");

            if (_viewModel.CallAction == VidyoCallAction.VidyoCallActionConnect)
                ConnectCall();
            else
                DisconnectCall();
        }

        void ConnectCall()
        {
            _logger.Log("DEBUG: V2MDVideoPage->ConnectCall");
            if (_viewModel.CallAction != VidyoCallAction.VidyoCallActionConnect) return;
            _viewModel.ToolbarStatus = "Connecting...";

            if (!_vidyoController.Connect(_viewModel.Host, _viewModel.Token, _viewModel.DisplayName, _viewModel.ResourceId))
                VidyoConnectorState = VidyoConnectorState.VidyoConnectorStateConnectionFailure;

            else
            {
                _viewModel.CallAction = VidyoCallAction.VidyoCallActionDisconnect;

                // Display the spinner animation
                _viewModel.LoadingPopupVisible(true);
                //_connectionSpinner.IsRunning = true;
            }
        }

        void DisconnectCall()
        {
            _logger.Log("DEBUG: V2MDVideoPage->DisconnectCall");
            _viewModel.ToolbarStatus = "Disconnecting...";
            _vidyoController?.Disconnect();
        }


here is vidyo controller : https://we.tl/t-BvHedkTTeU

can you please confirm where i am making mistake..

Thanks

**Comment by pfuternik** [comment]
Hi, can you please put breakpoints in your code to see exactly where it crashed? Also, if you have a stack trace that would also be helpful.

Lastly, please ensure that you are using our latest released libraries (version 4.1.25.17), which you can acquire here: https://developer.vidyo.io/#/packages

Are you seeing the crash when running https://github.com/Vidyo/VidyoConnector-xamarin without modifications?
