### ISSUE TITLE
the name MarshalPtrToUtf8 does not exist in the current context

### ISSUE THREAD

**Issue by carbon-paulc** [Vidyo/VidyoConnector-xamarin#16]
Hi,
I've just cloned the sample and followed the instructions, however, when trying to build I'm getting quite a few of these errors:
"the name MarshalPtrToUtf8 does not exist in the current context"

Is the MarshalPtrToUtf8 class meant to exist in a library somewhere?

**Comment by pfuternik** [comment]
Hello, thanks for the heads up. I've updated both the iOS and Android projects to now include the proper source file - MarshalPtrToUtf8.cs. If you pull the latest version of the Android and iOS SDK files, this file will be present in the include/csharp directory.
