### ISSUE TITLE
Build size: +460 MB

### ISSUE THREAD

**Issue by jmosbech** [Vidyo/VidyoConnector-xamarin#2]
Hi there!

When building the VidyoConnector sample in release mode it takes up more than 460 MB of space on my phone.

Is this intentional? And is there any way to reduce the size when implementing Vidyo in my own app?

**Comment by pfuternik** [comment]
Hi Jonas,

I'm glad that you were able to figure out how to make the app smaller. I will share your findings to the community:

_It appears that running the app through Apple's thinning process strips down the bundle to an acceptable size (below 100MB). The thinning does not happen when you deploy to your device through Visual Studio - even if it's built in Release mode.

However, if I choose "Archive for publishing", create an xarchive and use that to create an Ad Hoc bundle then the size is much smaller._

Thanks,
Philip
