### ISSUE TITLE
.dylib file issue - cant release on appstore 

### ISSUE THREAD

**Issue by patadia** [Vidyo/VidyoConnector-xamarin#4]
i have integrated Vidyo.io with my app.
libvidyoclient.dylib making that file build  as bundleresource 
its working perfectly fine with debug mode but when i make appstore app for release it did not getting upload because of this error

![screen shot 2018-01-03 at 12 32 55 pm](https://user-images.githubusercontent.com/7286934/34517123-bcc5add8-f09f-11e7-9dbe-827f2237e09b.png)

**Comment by pfuternik** [comment]
Hi Patadia,

We have removed the dylib and are now using static libraries instead, which will allow you to submit the app to the app store. The instructions are in the README on the main page https://github.com/Vidyo/VidyoConnector-xamarin ... Let me know if using the static libs solves your issue.

Best,
Phil
