### ISSUE TITLE
Issue Android

### ISSUE THREAD

**Issue by josebarrontovar** [Vidyo/VidyoConnector-xamarin#8]
I have a error in class Connector ,line "ConnectorPKG.SetApplicationUIContext(Forms.Context as Activity"
when that line is executed , go to line findClass ("com / vidyo / vidyoconnector ....").
in that line where the class seeks the application closes, some recommendation?

**Comment by tmelko-vidyo** [comment]
You forget to set the "Build Action" of **vidyoclient.jar** library. 
You have to do this for all "*.so" libraries as well.

Please follow these import steps from instructions:
- For Mac OS: **5 - 9** steps
- For Windows: **4 - 7** steps

https://github.com/Vidyo/VidyoConnector-xamarin
